sudo: required
dist: trusty
language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
addons:
  apt:
    packages:
      - abi-compliance-checker
      - autoconf
      - automake
      - autopoint
      - gengetopt
      - git
      - git2cl
      - gperf
      - gtk-doc-tools
      - lcov
      - libc6
      - libtool
      - libunistring-dev
      - libunistring0
      - ruby-ronn
      - texinfo
      - valgrind
before_install:
  - gem install bundler -v 1.16.1
  - curl -sS https://ftp.gnu.org/gnu/gettext/gettext-0.19.8.1.tar.xz | tar xJ
  - cd gettext-0.19.8.1
  - ./configure --quiet --disable-acl
  - make -s V=1
  - sudo make -s install
  - cd ..
  - git clone --depth 1 --recursive https://gitlab.com/libidn/libidn2
  - cd libidn2
  - sh bootstrap
  - ./configure --disable-doc
  - sudo make install

